### ISSUE TITLE
Where should plots and plotting scripts go?

### ISSUE THREAD

**Issue by rmatsum836** [nashville-data-nerds/think_tennessee#21]
I'm getting ready to push a couple commits of plots and scripts, but I want to make sure they're placed in the right directory before doing so.

I'm seeing `development`, and `documents` directories, should they go in either of these directories?  Or should we have a separate directory for all of the plotting stuff?

**Comment by alex-antonison** [comment]
@rmatsum836 - I have clarified in the https://github.com/nashville-data-nerds/think_tennessee/blob/master/How_To.md on submitting code and notebooks.

**Comment by rmatsum836** [comment]
Makes sense, thanks!
